package com.parkspot.werkins.service;
import com.parkspot.werkins.dto.*; import com.parkspot.werkins.entity.*; import com.parkspot.werkins.exception.*; import com.parkspot.werkins.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class VisitorVehicleService {
 private final VisitorVehicleRepository visits; private final FlatRepository flats; private final ParkingSlotRepository slots;
 public VisitorVehicleService(VisitorVehicleRepository v,FlatRepository f,ParkingSlotRepository s){visits=v;flats=f;slots=s;}
 @Transactional public VisitorResponse entry(VisitorEntryRequest r){String flatNumber=r.flatNumber().trim();Flat f=flats.findByFlatNumberIgnoreCase(flatNumber).orElseThrow(()->new ResourceNotFoundException("Flat not found: "+flatNumber));ParkingSlot s=slots.findById(r.parkingSlotId()).orElseThrow(()->new ResourceNotFoundException("Selected parking slot no longer exists. Please refresh and select another slot."));if(!s.isActive())throw new BusinessRuleException("Slot "+s.getSlotNumber()+" is no longer available. Please select another slot.");if(visits.existsByParkingSlotIdAndExitTimeIsNull(s.getId()))throw new BusinessRuleException("Slot "+s.getSlotNumber()+" is no longer available. Please select another slot.");if(visits.existsByVehicleNumberIgnoreCaseAndExitTimeIsNull(r.vehicleNumber()))throw new BusinessRuleException("Vehicle already has an active visit");VisitorVehicle v=new VisitorVehicle();v.setVehicleNumber(r.vehicleNumber().trim());v.setVisitorName(r.visitorName()==null||r.visitorName().isBlank()?"Visitor":r.visitorName().trim());v.setFlat(f);v.setParkingSlot(s);v.setEntryTime(r.entryTime()==null?LocalDateTime.now():r.entryTime());return out(visits.save(v));}
 @Transactional public VisitorResponse exit(Long id,ExitRequest req){VisitorVehicle v=visits.findById(id).orElseThrow(()->new ResourceNotFoundException("Visitor record not found: "+id));if(v.getExitTime()!=null)throw new BusinessRuleException("Vehicle has already exited");LocalDateTime t=req==null||req.exitTime()==null?LocalDateTime.now():req.exitTime();if(t.isBefore(v.getEntryTime()))throw new BusinessRuleException("Exit time cannot be before entry time");v.setExitTime(t);return out(visits.save(v));}
 public List<VisitorResponse> daily(LocalDate d){LocalDate day=d==null?LocalDate.now():d;return visits.findByEntryTimeBetweenOrderByEntryTimeDesc(day.atStartOfDay(),day.plusDays(1).atStartOfDay()).stream().map(this::out).toList();}
 public List<VisitorResponse> occupied(){return visits.findByExitTimeIsNullOrderByEntryTimeAsc().stream().map(this::out).toList();}
 private VisitorResponse out(VisitorVehicle v){return new VisitorResponse(v.getId(),v.getVehicleNumber(),v.getVisitorName(),v.getFlat().getId(),v.getFlat().getFlatNumber(),v.getParkingSlot().getId(),v.getParkingSlot().getSlotNumber(),v.getEntryTime(),v.getExitTime());}
}
